# Generated by Django 5.1 on 2024-09-06 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_orders_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='products',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.basket'),
        ),
    ]
