# Generated by Django 5.1 on 2024-09-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_orders_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='products',
            field=models.TextField(blank=True, null=True),
        ),
    ]
