# Generated by Django 5.1 on 2024-09-06 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_orders_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name': 'order', 'verbose_name_plural': 'orders'},
        ),
        migrations.AlterField(
            model_name='orders',
            name='index',
            field=models.CharField(max_length=6),
        ),
    ]
