# Generated by Django 5.1 on 2024-09-09 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_orders_options_alter_orders_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='total_sum',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
